# Generated by Django 5.1.1 on 2024-12-03 06:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Cargo')),
                ('es_cargo_principal', models.BooleanField(default=False)),
                ('orden_jerarquico', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoDirectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Período Activo'), ('FINALIZADO', 'Período Finalizado'), ('PLANEANDO', 'En Planificación')], default='PLANEANDO', max_length=20)),
            ],
        ),
   
        migrations.CreateModel(
            name='SeccionIglesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('JOVENES', 'Sociedad de Jóvenes'), ('CABALLEROS', 'Sociedad de Caballeros'), ('DAMAS', 'Sociedad de Damas')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NOMBRE')),
                ('lastname', models.CharField(max_length=50, verbose_name='APELLIDOS')),
                ('dni', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='CEDULA')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=15, verbose_name='GENERO')),
                ('date_joined', models.DateField(verbose_name='FECHA DE NACIMIENTO')),
                ('address', models.CharField(max_length=150, verbose_name='DIRECCION')),
                ('fecha_ingreso', models.DateField(verbose_name='FECHA DE INGRESO')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='TELEFONO')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='CORREO ELECTRONICO')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='IMAGEN')),
                ('category', models.CharField(choices=[('joven', 'Joven'), ('dama', 'Dama'), ('caballero', 'Caballero'), ('adolecente', 'Adolecente')], max_length=20, verbose_name='CATEGORIA')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo', verbose_name='CARGO')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado', verbose_name='ESTADO')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'miembro',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MiembroStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enfermo', 'Miembro se encuentra enfermo'), ('visitar', 'Miembro necesita ser visitado'), ('permiso', 'Miembro tiene permiso o excusa')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.miembro')),
            ],
            options={
                'verbose_name': 'StatusMiembro',
                'verbose_name_plural': 'StatusMiembros',
            },
        ),
        migrations.CreateModel(
            name='ProcesoTransicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PREPARACION', 'En Preparación'), ('INSCRIPCION', 'Inscripción de Candidatos'), ('VOTACION', 'Proceso de Votación'), ('CONFIRMACION', 'Confirmación'), ('COMPLETADO', 'Proceso Completado')], default='PREPARACION', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_planeada', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('periodo_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicion_anterior', to='app.periododirectiva')),
                ('periodo_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicion_nuevo', to='app.periododirectiva')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seccioniglesia')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFinanzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_miembros_recibidos', models.IntegerField(default=0)),
                ('total_fondos_recibidos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periododirectiva')),
            ],
        ),
        migrations.AddField(
            model_name='periododirectiva',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seccioniglesia'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='app.seccioniglesia'),
        ),
        
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Titulo de la actividad')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(verbose_name='Ingresa la fecha de la actividad')),
                ('completado', models.BooleanField(default=False, verbose_name='¿Tarea completada?')),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('present', models.BooleanField(default=False)),
                ('day_of_week', models.CharField(blank=True, editable=False, max_length=10, verbose_name='DÍA DE LA SEMANA')),
                ('attendance_type', models.CharField(choices=[('GEN', 'General'), ('YTH', 'Jóvenes'), ('LDS', 'Damas'), ('GNT', 'Caballeros')], default='GEN', max_length=3, verbose_name='TIPO DE ASISTENCIA')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.miembro')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'unique_together': {('miembro', 'date', 'attendance_type')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionDirectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.miembro')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periododirectiva')),
            ],
            options={
                'unique_together': {('miembro', 'cargo', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='CandidatoTransicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.IntegerField(default=0)),
                ('cargo_postulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.miembro')),
                ('proceso_transicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.procesotransicion')),
            ],
            options={
                'unique_together': {('proceso_transicion', 'miembro', 'cargo_postulado')},
            },
        ),
    ]
