# Generated by Django 5.1.1 on 2025-02-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesotransicion',
            name='seccion',
            field=models.CharField(choices=[('JOVENES', 'Sociedad de Jóvenes'), ('CABALLEROS', 'Sociedad de Caballeros'), ('DAMAS', 'Sociedad de Damas'), ('GENERAL', 'Servicio General')], default='JOVENES', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='periododirectiva',
            name='seccion',
            field=models.CharField(choices=[('JOVENES', 'Sociedad de Jóvenes'), ('CABALLEROS', 'Sociedad de Caballeros'), ('DAMAS', 'Sociedad de Damas'), ('GENERAL', 'Servicio General')], default='JOVENES', max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='SeccionIglesia',
        ),
    ]
