# Generated by Django 4.2.19 on 2025-03-07 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='usuario_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicio',
            name='director_cultural',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_dirigidos', to='app.persona', verbose_name='DIRECTOR DEL CULTURAL'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='eventos_participados', to='app.persona', verbose_name='PARTICIPANTES DEL CULTURA'),
        ),
        migrations.AddField(
            model_name='registrofinanzas',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periododirectiva'),
        ),
        migrations.AddField(
            model_name='procesotransicion',
            name='periodo_anterior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicion_anterior', to='app.periododirectiva'),
        ),
        migrations.AddField(
            model_name='procesotransicion',
            name='periodo_nuevo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicion_nuevo', to='app.periododirectiva'),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('nombre', 'apellido')},
        ),
        migrations.AddField(
            model_name='miembro',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo', verbose_name='CARGO'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado', verbose_name='ESTADO'),
        ),
        migrations.AddField(
            model_name='estudiobiblico',
            name='maestro',
            field=models.ForeignKey(limit_choices_to={'cargo__nombre': 'Maestro'}, on_delete=django.db.models.deletion.PROTECT, related_name='estudios_impartidos', to='app.miembro'),
        ),
        migrations.AddField(
            model_name='estudiobiblico',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró'),
        ),
        migrations.AddField(
            model_name='candidatotransicion',
            name='cargo_postulado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo'),
        ),
        migrations.AddField(
            model_name='candidatotransicion',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.miembro'),
        ),
        migrations.AddField(
            model_name='candidatotransicion',
            name='proceso_transicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.procesotransicion'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.miembro', verbose_name='Miembro'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró'),
        ),
        migrations.AddField(
            model_name='asistenciaestudio',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.miembro', verbose_name='Miembro'),
        ),
        migrations.AddField(
            model_name='asistenciaestudio',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró'),
        ),
        migrations.AddField(
            model_name='asignaciondirectiva',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo'),
        ),
        migrations.AddField(
            model_name='asignaciondirectiva',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.miembro'),
        ),
        migrations.AddField(
            model_name='asignaciondirectiva',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periododirectiva'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatotransicion',
            unique_together={('proceso_transicion', 'miembro', 'cargo_postulado')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'attendance_type'], name='app_attenda_date_d7a085_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['miembro', 'date'], name='app_attenda_miembro_8e8303_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['present', 'date'], name='app_attenda_present_bb07fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('miembro', 'date', 'attendance_type')},
        ),
        migrations.AddIndex(
            model_name='asistenciaestudio',
            index=models.Index(fields=['date', 'attendance_type'], name='app_asisten_date_3acd55_idx'),
        ),
        migrations.AddIndex(
            model_name='asistenciaestudio',
            index=models.Index(fields=['miembro', 'date'], name='app_asisten_miembro_288493_idx'),
        ),
        migrations.AddIndex(
            model_name='asistenciaestudio',
            index=models.Index(fields=['presente', 'date'], name='app_asisten_present_36ee40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaestudio',
            unique_together={('miembro', 'date', 'attendance_type')},
        ),
        migrations.AlterUniqueTogether(
            name='asignaciondirectiva',
            unique_together={('miembro', 'cargo', 'periodo')},
        ),
    ]
