# Generated by Django 5.0.6 on 2024-08-30 16:54

from django.db import migrations


def create_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Jovenes_Secretary')
    Group.objects.get_or_create(name='Caballeros_Secretary')
    Group.objects.get_or_create(name='Damas_Secretary')
    Group.objects.get_or_create(name='General_Secretary')

class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]


