# Generated by Django 5.0.3 on 2024-08-09 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directivacargo',
            name='cambio_directiva',
        ),
        migrations.RemoveField(
            model_name='directivacargo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='directivacargo',
            name='miembro',
        ),
        migrations.DeleteModel(
            name='CambioDirectiva',
        ),
        migrations.DeleteModel(
            name='DirectivaCargo',
        ),
    ]
