# Generated by Django 5.1.1 on 2024-12-23 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'miembro'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Inasistencia'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('GEN', 'General'), ('YTH', 'Jóvenes'), ('LDS', 'Damas'), ('GNT', 'Caballeros')], default='GEN', max_length=3, verbose_name='Tipo de Asistencia'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day_of_week',
            field=models.CharField(blank=True, editable=False, max_length=10, verbose_name='Día de la Semana'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.miembro', verbose_name='Miembro'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=False, verbose_name='Presente'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'attendance_type'], name='app_attenda_date_d7a085_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['miembro', 'date'], name='app_attenda_miembro_8e8303_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['present', 'date'], name='app_attenda_present_bb07fa_idx'),
        ),
    ]
