# Generated by Django 5.1.4 on 2025-02-21 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nino', models.CharField(max_length=100, verbose_name='Nombre del Niño')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('lugar_nacimiento', models.CharField(max_length=200, verbose_name='Lugar de Nacimiento')),
                ('nombre_padre', models.CharField(max_length=100, verbose_name='Nombre del Padre')),
                ('nombre_madre', models.CharField(max_length=100, verbose_name='Nombre de la Madre')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('fecha_presentacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Presentación')),
                ('pastor_oficiante', models.CharField(max_length=100, verbose_name='Pastor Oficiante')),
                ('testigos', models.TextField(blank=True, verbose_name='Testigos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Presentación de Niño',
                'verbose_name_plural': 'Presentaciones de Niños',
            },
        ),
    ]
