# Generated by Django 5.1.1 on 2024-12-31 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_attendance_options_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiembroStatus',
        ),
    ]
