# Generated by Django 5.0.3 on 2024-08-09 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_directivacargo_cambio_directiva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioDirectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_miembros_recibidos', models.IntegerField(verbose_name='Cantidad de Miembros Recibidos')),
                ('fondos_recibidos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fondos Recibidos')),
                ('fecha_cambio', models.DateField(auto_now_add=True, verbose_name='Fecha de Cambio')),
            ],
            options={
                'verbose_name': 'Cambio de Directiva',
                'verbose_name_plural': 'Cambios de Directiva',
                'db_table': 'cambio_directiva',
                'ordering': ['fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='DirectivaCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio_directiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cambiodirectiva')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.miembro')),
            ],
        ),
    ]
