# Generated by Django 5.0.6 on 2024-08-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_create_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cambiodirectiva',
            options={'ordering': ['fecha_cambio'], 'verbose_name': 'Cambio de Directiva', 'verbose_name_plural': 'Cambios de Directivas'},
        ),
    ]
