# Generated by Django 5.1.1 on 2024-10-11 05:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_create_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directivacargo',
            name='cambio_directiva',
        ),
        migrations.RemoveField(
            model_name='directivacargo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='directivacargo',
            name='miembro',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('GEN', 'General'), ('YTH', 'Jóvenes'), ('LDS', 'Damas'), ('GNT', 'Caballeros')], default='GEN', max_length=3, verbose_name='TIPO DE ASISTENCIA'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('miembro', 'date', 'attendance_type')},
        ),
        migrations.DeleteModel(
            name='CambioDirectiva',
        ),
        migrations.DeleteModel(
            name='DirectivaCargo',
        ),
    ]
