# Generated by Django 5.0.6 on 2024-09-27 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_create_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directivacargo',
            name='cambio_directiva',
        ),
        migrations.RemoveField(
            model_name='directivacargo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='directivacargo',
            name='miembro',
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CambioDirectiva',
        ),
        migrations.DeleteModel(
            name='DirectivaCargo',
        ),
    ]
