# Generated by Django 4.2.19 on 2025-02-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_presentacionnino'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacionnino',
            name='acta_nacimiento',
            field=models.FileField(blank=True, help_text='Puede subir el acta de nacimiento en formato PDF o imagen', null=True, upload_to='actas_nacimiento/', verbose_name='Acta de Nacimiento'),
        ),
    ]
