# Generated by Django 5.1.1 on 2025-02-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_periododirectiva_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesotransicion',
            name='seccion',
            field=models.CharField(choices=[('JOVENES', 'Sociedad de Jóvenes'), ('CABALLEROS', 'Sociedad de Caballeros'), ('DAMAS', 'Sociedad de Damas'), ('GENERAL', 'Servicio General')], default='JOVENES', max_length=50),
        ),
    ]
