# Generated by Django 5.0.6 on 2024-09-06 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cambiodirectiva_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directivacargo',
            name='cambio_directiva',
        ),
        migrations.RemoveField(
            model_name='directivacargo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='directivacargo',
            name='miembro',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CambioDirectiva',
        ),
        migrations.DeleteModel(
            name='DirectivaCargo',
        ),
    ]
