# Generated by Django 4.2.19 on 2025-03-13 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('diezmo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ofrenda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro Financiero',
                'verbose_name_plural': 'Registros Financieros',
                'ordering': ['-fecha'],
            },
        ),
    ]
