# Generated by Django 5.1.1 on 2025-01-03 01:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_miembrostatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='NOMBRE')),
                ('apellido', models.CharField(max_length=100, verbose_name='APELLIDO')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['nombre', 'apellido'],
                'unique_together': {('nombre', 'apellido')},
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('JOVENES', 'Sociedad de Jóvenes'), ('CABALLEROS', 'Sociedad de Caballeros'), ('DAMAS', 'Sociedad de Damas')], max_length=20, verbose_name='TIPO DE SERVICIO')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='FECHA DE SERVICIO')),
                ('direccion', models.CharField(max_length=50, verbose_name='DIRECCIÓN DEL CULTO')),
                ('lectura', models.TextField(max_length=50, verbose_name='LECTURA DE LA PALABRA')),
                ('devocional', models.TextField(max_length=50, verbose_name='DEVOCIONAL')),
                ('mensaje', models.TextField(max_length=50, verbose_name='MENSAJE DE LA PALABRA')),
                ('ofrenda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='OFRENDA')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='DESCRIPCIÓN')),
                ('director_cultural', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_dirigidos', to='app.persona', verbose_name='DIRECTOR DEL CULTURAL')),
                ('participantes', models.ManyToManyField(blank=True, related_name='eventos_participados', to='app.persona', verbose_name='PARTICIPANTES DEL CULTURAL')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-fecha'],
            },
        ),
    ]
