# Generated by Django 5.1.5 on 2025-01-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_persona_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='ofrenda',
            field=models.CharField(max_length=13, verbose_name='OFRENDA'),
        ),
    ]
