# Generated by Django 5.0.3 on 2024-09-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='day_of_week',
            field=models.CharField(blank=True, editable=False, max_length=10, verbose_name='DÍA DE LA SEMANA'),
        ),
    ]
