# Generated by Django 5.1.1 on 2025-02-02 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_servicio_ofrenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='seccion',
            field=models.ForeignKey(default='GENERAL', on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='app.seccioniglesia'),
        ),
        migrations.AlterField(
            model_name='seccioniglesia',
            name='nombre',
            field=models.CharField(choices=[('JOVENES', 'Sociedad de Jóvenes'), ('CABALLEROS', 'Sociedad de Caballeros'), ('DAMAS', 'Sociedad de Damas'), ('GENERAL', 'Servicio General')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('JOVENES', 'Sociedad de Jóvenes'), ('CABALLEROS', 'Sociedad de Caballeros'), ('DAMAS', 'Sociedad de Damas'), ('GENERAL', 'Servicio General')], max_length=20, verbose_name='TIPO DE SERVICIO'),
        ),
    ]
