# Generated by Django 5.0.6 on 2024-08-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_attendance_usuario_asignado_alter_tarea_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='usuario_asignado',
        ),
    ]
